language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
#  - "3.4" # Wait for fix: https://github.com/travis-ci/travis-ci/issues/1989
  - "pypy"
matrix:
  allow_failures:
    - python:
       - "2.6"
    - python:
       - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests --verbose --with-coverage --cover-package=coursera

after_success:
  coveralls
